import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from "@/redux/provider"
import { Setup } from '@/components/utils';
import { Navbar } from "@/components/common";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
